name: minisim test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  full-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Build
        run: make build

      - name: Run checks
        run: make check